"""Remove order in packets.

Revision ID: 38100e45dcf8
Revises: 6ca8e399c7d7
Create Date: 2025-03-13 12:38:19.524844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38100e45dcf8'
down_revision: Union[str, None] = '6ca8e399c7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_packets', 'order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_packets', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
