"""Add IP src Dos and Portscan schema

Revision ID: 3c86b41f0a7e
Revises: 6b90e03c6017
Create Date: 2025-03-18 13:27:35.819297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c86b41f0a7e'
down_revision: Union[str, None] = '6b90e03c6017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dos_predictions', sa.Column('ip_src', sa.String(), nullable=True))
    op.add_column('portscan_predictions', sa.Column('ip_src', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portscan_predictions', 'ip_src')
    op.drop_column('dos_predictions', 'ip_src')
    # ### end Alembic commands ###
