"""add intrusion table

Revision ID: 631ef6b66416
Revises: a8248b4b2251
Create Date: 2025-03-06 16:45:17.301069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '631ef6b66416'
down_revision: Union[str, None] = 'a8248b4b2251'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrusion_predictions',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prediction', sa.String(), nullable=True),
    sa.Column('fid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intrusion_predictions')
    # ### end Alembic commands ###
