"""Create Dos and Portscan schema

Revision ID: 6b90e03c6017
Revises: c7157d312e5f
Create Date: 2025-03-18 13:17:41.184822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b90e03c6017'
down_revision: Union[str, None] = 'c7157d312e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dos_predictions',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('timestamp_end', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_dos_predictions_timestamp_end'), 'dos_predictions', ['timestamp_end'], unique=False)
    op.create_index(op.f('ix_dos_predictions_timestamp_start'), 'dos_predictions', ['timestamp_start'], unique=False)
    op.create_table('portscan_predictions',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp_start', sa.TIMESTAMP(), nullable=True),
    sa.Column('timestamp_end', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_portscan_predictions_timestamp_end'), 'portscan_predictions', ['timestamp_end'], unique=False)
    op.create_index(op.f('ix_portscan_predictions_timestamp_start'), 'portscan_predictions', ['timestamp_start'], unique=False)
    op.drop_index('ix_intrusion_predictions_timestamp', table_name='intrusion_predictions')
    op.drop_table('intrusion_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intrusion_predictions',
    sa.Column('uid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prediction', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('uid', name='intrusion_predictions_pkey')
    )
    op.create_index('ix_intrusion_predictions_timestamp', 'intrusion_predictions', ['timestamp'], unique=False)
    op.drop_index(op.f('ix_portscan_predictions_timestamp_start'), table_name='portscan_predictions')
    op.drop_index(op.f('ix_portscan_predictions_timestamp_end'), table_name='portscan_predictions')
    op.drop_table('portscan_predictions')
    op.drop_index(op.f('ix_dos_predictions_timestamp_start'), table_name='dos_predictions')
    op.drop_index(op.f('ix_dos_predictions_timestamp_end'), table_name='dos_predictions')
    op.drop_table('dos_predictions')
    # ### end Alembic commands ###
