"""Change column type to JSONB, add src/dst Ip and port to packet.

Revision ID: 6ca8e399c7d7
Revises: c2062b0fb3c4
Create Date: 2025-03-13 12:24:23.335930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ca8e399c7d7'
down_revision: Union[str, None] = 'c2062b0fb3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_flows', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('network_packets', sa.Column('srcIp', sa.String(), nullable=True))
    op.add_column('network_packets', sa.Column('srcPort', sa.Integer(), nullable=True))
    op.add_column('network_packets', sa.Column('dstIp', sa.String(), nullable=True))
    op.add_column('network_packets', sa.Column('dstPort', sa.Integer(), nullable=True))
    op.alter_column('network_packets', 'layers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('network_packets', 'layers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('network_packets', 'dstPort')
    op.drop_column('network_packets', 'dstIp')
    op.drop_column('network_packets', 'srcPort')
    op.drop_column('network_packets', 'srcIp')
    op.alter_column('network_flows', 'data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
