"""Initial migration

Revision ID: a8248b4b2251
Revises: 
Create Date: 2025-03-06 11:15:24.889145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8248b4b2251'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_packets',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('layers', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_network_packets_timestamp'), 'network_packets', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_packets_timestamp'), table_name='network_packets')
    op.drop_table('network_packets')
    # ### end Alembic commands ###
