"""add timestamp in intrusion table

Revision ID: b0e5db2b66c1
Revises: 631ef6b66416
Create Date: 2025-03-06 16:49:32.465863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0e5db2b66c1'
down_revision: Union[str, None] = '631ef6b66416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intrusion_predictions', sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_intrusion_predictions_timestamp'), 'intrusion_predictions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_intrusion_predictions_timestamp'), table_name='intrusion_predictions')
    op.drop_column('intrusion_predictions', 'timestamp')
    # ### end Alembic commands ###
