"""Add network flows table

Revision ID: c2062b0fb3c4
Revises: b0e5db2b66c1
Create Date: 2025-03-12 10:15:44.747241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2062b0fb3c4'
down_revision: Union[str, None] = 'b0e5db2b66c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_flows',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fid', sa.String(), nullable=True),
    sa.Column('srcIp', sa.String(), nullable=True),
    sa.Column('srcPort', sa.Integer(), nullable=True),
    sa.Column('dstIp', sa.String(), nullable=True),
    sa.Column('dstPort', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_network_flows_timestamp'), 'network_flows', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_network_flows_timestamp'), table_name='network_flows')
    op.drop_table('network_flows')
    # ### end Alembic commands ###
