"""Add duration column in network flows

Revision ID: c7157d312e5f
Revises: 33bef2dd27ce
Create Date: 2025-03-15 10:30:46.476139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7157d312e5f'
down_revision: Union[str, None] = '33bef2dd27ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('network_flows', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('network_flows', 'duration')
    # ### end Alembic commands ###
